<?xml version="1.0"?>

<robot name="bot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:arg name="robot_namespace" default="/" /> 

  <xacro:include filename="$(find bot_description)/urdf/wheel.urdf.xacro" />
  

  <!-- Variables -->
  <xacro:property name="M_PI" value="3.1415926"/>

  <!-- Vehicle Geometries -->
  <xacro:property name="base_x_size" value="0.9250000" />
  <xacro:property name="base_y_size" value="0.380000" />
  <xacro:property name="base_z_size" value="0.210000" />

  <xacro:property name="wheelbase" value="0.498" />
  <xacro:property name="wheeltrack" value="0.58306" />
  <xacro:property name="wheel_vertical_offset" value="-0.0702" />

  <xacro:property name="wheel_length" value="1.1653e-01" />
  <xacro:property name="wheel_radius" value="1.6459e-01" />

  <!-- Base link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://bot_description/meshes/base_link.dae" />
      </geometry>
    </visual>
    <collision>
        <origin xyz="0 0 0.008" rpy="0 0 0" />
      <geometry>
        <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
      </geometry>
    </collision>
    <collision>
      <origin xyz="0 0 ${base_z_size/6}" rpy="0 0 0" />
      <geometry>
        <box size="${base_x_size/6} ${base_y_size*1.65} ${base_z_size/3}"/>
      </geometry>
    </collision>
  </link>

  <link name="base_footprint"/>

  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 ${wheel_vertical_offset - wheel_radius}" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="base_footprint" />
  </joint>

  <link name="inertial_link">
    <inertial>
      <mass value="40" />
      <origin xyz="0.0 0.0 0.0" />
      <inertia ixx="2.288641" ixy="0"         ixz="0" 
                              iyy="5.103976"  iyz="0" 
                                              izz="3.431465" />
    </inertial>
  </link>

  <joint name="inertial_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="inertial_link" />
  </joint>


  <link name="rslidar_link">
    <visual>
        <origin xyz="0.0 0.0 0.0" />
        <geometry>
            <cylinder length="0.05" radius="0.03" />
        </geometry>
    </visual>
  </link>
  <joint name="rslidar_joint" type="fixed">
    <origin xyz="0.2 0 0.5" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="rslidar_link" />
  </joint>

  <link name="imu_link">
    <!-- <visual>
        <origin xyz="0.0 0.0 0.0" />
        <geometry>
            <cylinder length="0.05" radius="0.03" />
        </geometry>
    </visual> -->
  </link>
  <joint name="imu_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="imu_link" />
  </joint>

  <xacro:scout_wheel wheel_prefix="front_right">
    <origin xyz="${wheelbase/2} ${-wheeltrack/2} ${wheel_vertical_offset}" rpy="${M_PI} 0 0" />
    <axis xyz="0 -1 0" rpy="0 0 0" />
  </xacro:scout_wheel>
  <xacro:scout_wheel wheel_prefix="rear_right">
    <origin xyz="${-wheelbase/2} ${-wheeltrack/2} ${wheel_vertical_offset}" rpy="${M_PI} 0 0" />
    <axis xyz="0 -1 0" rpy="0 0 0" />
  </xacro:scout_wheel>

  <xacro:scout_wheel wheel_prefix="front_left">
    <origin xyz="${wheelbase/2} ${wheeltrack/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    <axis xyz="0 1 0" rpy="0 0 0" />
  </xacro:scout_wheel>
  <xacro:scout_wheel wheel_prefix="rear_left">
    <origin xyz="${-wheelbase/2} ${wheeltrack/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    <axis xyz="0 1 0" rpy="0 0 0" />
  </xacro:scout_wheel>


  <!-- <xacro:include filename="$(find bot_description)/urdf/scout_sensor.urdf.xacro" /> -->

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>$(arg robot_namespace)</robotNamespace>
      <legacyModeNS>true</legacyModeNS>
    </plugin>
  </gazebo>

  <!-- <gazebo >
    <static value="false" />
  </gazebo> -->


</robot>
