footprint: [[-0.465,-0.3495], [-0.465,0.3495],[0.465,0.3495],[0.465,-0.3495]]
footprint_padding: 0.01 

robot_base_frame: base_link
transform_tolerance: 0.5         #Specifies the delay in transform (tf) data that is tolerable in seconds.

#Rate parameters
# update_frequency: 10.0           #The frequency in Hz for the map to be updated. 
# publish_frequency: 10.0          #The frequency in Hz for the map to be publish display information.

#The following parameters can be overwritten by some layers, namely the static map layer. 
width: 10
height: 10
origin_x: 0.0
origin_y: 0.0
resolution: 0.05




#layer definitions
static_layer:
  map_topic: /map
  subscribe_to_updates: true       #In addition to map_topic, also subscribe to map_topic + "_updates"
  track_unknown_space : true       #(bool, default: true) if false,unknown values are translated as FREE_SPACE in the layer. 
  trinary_costmap : true           #(bool, default: true)  NO_INFORMATION/FREE_SPACE/LETHAL_OBSTACLE (three values)

obstacle_layer:
  observation_sources: laser
  laser: 
    data_type: LaserScan
    clearing: true
    marking: true
    topic: scan
    inf_is_valid: true         #The Inf values are converted to the laser maximum range. 
    max_obstacle_height: 1.0   #Setting this parameter to a value greater than the global max_obstacle_height parameter has no effect. 
    min_obstacle_height: 0.0   #(double, default: 0.0)
    obstacle_range: 2.5     
    raytrace_range: 3.0

  #Global Filtering Parameters   These parameters apply to all sensors. 
  max_obstacle_height: 1.0
  obstacle_range: 2.5       #The maximum range in meters at which to insert obstacles into the costmap using sensor data. 
  raytrace_range: 3.0       #The maximum range in meters at which to raytrace out obstacles from the map using sensor data. 
  
  # #The following parameters are used by the VoxelCostmapPlugin.
  # origin_z:             0.0
  # z_resolution:         0.2
  # z_voxels:             2
  # unknown_threshold:    15    #(default: ~<name>/z_voxels)
  # mark_threshold:       0
  # combination_method:   1
  # publish_voxel_map: false

  # #These parameters are used by the ObstacleCostmapPlugin.
  # track_unknown_space:  true    #true needed for disabling global path planning through unknown space

 
   

inflation_layer:
  inflation_radius: 0.5
  # cost_scaling_factor: 10     #(double, default: 10.0)
