local_costmap:
  global_frame: odom
  update_frequency: 5.0
  publish_frequency: 2.0

  static_map: false  
  rolling_window: true

  width: 8
  height: 8

  plugins:
    - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
  
